# Generated by Django 5.2.7 on 2025-10-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, verbose_name='Эл.почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('description', models.TextField(max_length=60, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Ссылка на фото')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name_plural': 'Мерч',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=10, verbose_name='Статус оплаты')),
                ('number_of_products', models.IntegerField(verbose_name='Количество товаров')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к оплате')),
                ('adress', models.CharField(verbose_name='Адрес')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Метод оплаты')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.client')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.event')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Ordering_of_goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_orders', models.IntegerField(verbose_name='Номер заказа')),
                ('merchandise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.merchandise')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.order')),
            ],
            options={
                'verbose_name_plural': 'Мерч в заказе',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.client')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.event')),
            ],
            options={
                'verbose_name_plural': 'Билет',
            },
        ),
    ]
