# Generated by Django 5.2.7 on 2025-10-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.event'),
        ),
    ]
