# Generated by Django 5.2.7 on 2025-10-08 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0002_alter_order_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slipiapp2.event'),
        ),
    ]
