# Generated by Django 5.2.7 on 2025-10-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0003_alter_order_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event_id',
        ),
    ]
