# Generated by Django 5.2.8 on 2025-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0004_remove_order_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='photo',
            field=models.ImageField(upload_to='merch/', verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='size',
            field=models.CharField(blank=True, max_length=10, verbose_name='Размер'),
        ),
    ]
