# Generated by Django 5.2.8 on 2025-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0005_alter_merchandise_photo_alter_merchandise_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='merchtypee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
