# Generated by Django 5.2.8 on 2025-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0006_merchandise_merchtypee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='merchtypee',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='merchtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип мерча'),
        ),
    ]
