# Generated by Django 5.2.8 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipiapp2', '0007_remove_merchandise_merchtypee_merchandise_merchtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='merchtype',
            field=models.CharField(default='Clothes', max_length=100, verbose_name='Тип мерча'),
            preserve_default=False,
        ),
    ]
